### ISSUE TITLE
Contribute to the Dashboard Initiative

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#10]
From @courtney in Slack at https://wordpress.slack.com/archives/C03JNV77Y57/p1695409071112679

> Hey folks, I'd like to get involved specifically on the social sustainability aspects and the efforts to create project dashboards with stats. I've got a post drafted and reviewed by 
[@harishanker](https://wordpress.slack.com/team/U1LT6BMEJ)
. I'll move it to a draft post on the team site and leave a comment with a link for review. I'd like a few regular members here to get eyes on it before taking it live and voice any concerns before it officially publishes. 

https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/

**Comment by gusaus** [comment]
So while it's still unclear if/how we can contribute (to this or any roadmap projects/ideas) as a team https://github.com/WordPress/sustainability/issues/13, @courtneyr-dev's [comment](https://make.wordpress.org/project/2023/12/12/overflow-questions-from-state-of-the-word-2023/#comment-472) in Matt's State of the Word Q&A overflow post indicates progress.

How/where can we contribute?

**Comment by gusaus** [comment]
Realizing this was never properly scoped (again - a process/template + dedicated PM would really help), we could probably move this into the 'done' column since the goal was limited to [providing feedback](https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/#comment-407).

Does that make sense?

**Comment by gusaus** [comment]
Does anyone know the status of the Dashboard Initiative?

**Comment by courtneyr-dev** [comment]
> Does anyone know the status of the Dashboard Initiative?

I should have a rough draft available by Wednesday of the current update, to be reviewed and available ahead of the team meeting on Friday.

**Comment by gusaus** [comment]
Appreciate the update, @courtneyr-dev!

Also would be good to know where collaboration is happening and who owns/manages the project (assuming its not us).

**Comment by gusaus** [comment]
Referencing the [update](https://make.wordpress.org/sustainability/2024/05/10/recognizing-contributions-and-acknowledging-challenges/) @courtneyr-dev posted in https://make.wordpress.org/sustainability
 
Does that mean our team owns or will help drive this effort?

**Comment by courtneyr-dev** [comment]
Helping to drive certainly. I have just gotten access to the demo of a tool, which will be shared in a second post early next week.
