### ISSUE TITLE
Enable/organize/contribute to NextGen and other Events related to Sustainability goals and focus areas

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#12]
### NextGen and other Event ideas and suggestions
Share and submit [event ideas and formats](https://wordpress.slack.com/docs/T024MFP4J/F05SUHSBWGZ) with the Community Team

- [x] #21
    - provide opportunities for new contributors and maintainers to receive hands-on training
    - enable organizations and contributors in specific interest areas or industry groups
    - create additional ways to support and sustain organizers, contributors, and participants
- [ ] #22 - Each quarterly round can have multiple focus areas with their own match fund. 
  * WordPress project and community - Participants could include any Make Team, Working Group, Community project, or program on [Open Collective](https://opencollective.com/) (stand-alone collective or project on the [WordPress Collective](https://wordpress.slack.com/docs/T024MFP4J/F0686TS707J)).
  * Specific interest areas (could be coupled with do_action) 
    * Education
    * Arts & Culture
    * Civic Tech
    * Mutual Aid
    * Publishing & Media
    * Music
- [ ] [WP and Friends Sustainability Hackday](https://wordpress.slack.com/docs/T024MFP4J/F05SUHSBWGZ?focus_section_id=temp:C:QaOedecd62ceec54724a22fb1d15) - An event for the open source community to come together, share challenges, and explore new solutions to make our efforts more sustainable.

### Contribute and help organize more ‘environmentally’ sustainable WordCamps, Meetups, and other events.
- [ ] https://github.com/WordPress/sustainability/issues/9
- [ ] https://github.com/WordPress/sustainability/issues/11

## Reference/resources
* [Sustainability Team: NextGen and other Event ideas and suggestions (Slack Canvas)](https://wordpress.slack.com/docs/T024MFP4J/F05SUHSBWGZ)
* [WordPress Sustainability Team: NextGen and other Event ideas and suggestions (Google Doc)](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit?usp=sharing)
* [The Next Generation of WordCamps](https://href.li/?https://make.wordpress.org/community/2023/05/08/the-next-generation-of-wordcamps/)
* [The NextGen Event Project: Your Ideas, Your WordPress Community!](https://make.wordpress.org/community/2023/08/30/the-nextgen-event-project-your-ideas-your-wordpress-community/)

**Comment by meeware** [comment]
Self assigning here.

I have been engaging with the nextgen events team and am proposing a sustainability extended hack day.

**Comment by gusaus** [comment]
@meeware I didn't realize you were working on this 👆until I skimmed through the recent meeting logs. I've been talking with some of the same folks on the community team but haven't circled back to see if/how we could contribute as a team... until now.

We should trade notes and figure out a path forward after the weekend 🎉🎬
