### ISSUE TITLE
Explore and enable options for funding community projects, teams, working groups, and contributors

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#15]
#### Open Source partnerships and collaboration
Explore partnership/collaboration with [The WP Community Collective](https://www.thewpcommunitycollective.com/about) and other organizations in the Open Collective/[Open source ecosystem](https://discover.opencollective.com/?tag=open+source) that support and fund individual contribution and community-based initiatives.

- [ ] [Open Source Collective](https://www.oscollective.org/)
- [ ] [Open Collective Foundation](https://opencollective.foundation/)
- [ ] [Sustain](https://sustainoss.org/)
- [ ] [CHAOSS](https://chaoss.community/)
- [ ] [FOSS Contributors](https://github.com/fosscontributors)

#### Leverage and extend Funding platforms and programs 
- [ ] #24 
- [ ] #22
- [ ] [GitHub Sponsors](https://github.com/sponsors) 
- [ ] [Gitcoin Grants](https://www.gitcoin.co/program)
- [ ] [Patreon](https://www.patreon.com/)
- [ ] [Tidelift](https://tidelift.com/)

### Reference/resources

- [Open Source and how we sustain ourselves](https://make.wordpress.org/project/2022/08/01/open-source-and-the-free-rider-problem/) ([WordPress.org Project](https://make.wordpress.org/project/))
- [Introduction to the economic pillar of sustainability](https://sustainwp.com/podcast/episode-4-introduction-to-the-economic-pillar-of-sustainability/) ([Sustain WP podcast](https://sustainwp.com/))
- [Sustaining and Growing WordPress through Open Collective](https://wordpress.slack.com/docs/T024MFP4J/F0686TS707J) (Making WordPress Slack)

**Comment by meeware** [comment]
Links to investment and other organisation with a focus on sustainability (need a LOT more of these!):

- [Sustainable Ventures](https://www.sustainableventures.co.uk/): London based VC, incubator, and consultancy focussed on sustainability. @meeware has contact there. [Green Web Foundation](https://www.thegreenwebfoundation.org/) are alumni
- [Climate Aligned](https://www.climatealigned.co/) - service matching investors to sustainable investments. @meeware has contact there.
-

**Comment by gusaus** [comment]
> Explore partnership/collaboration with [The WP Community Collective](https://www.thewpcommunitycollective.com/about) and other organizations in the Open Collective/[Open source ecosystem](https://discover.opencollective.com/?tag=open+source) that support and fund individual contribution and community-based initiatives.

Circling back to this as the recent dissolution of one of the primary fiscal sponsors in the Open Collective ecosystem has affected WPCC (see this [recent update](https://opencollective.com/thewpcc/updates/navigating-change-the-wpccs-search-for-a-new-fiscal-home-amidst-ocfs-dissolution) from @courtneyr-dev for context).

> [The WP Community Collective](https://www.thewpcommunitycollective.com/about) supports and funds individual contribution and community-based initiatives for the [open-source WordPress project](http://wordpress.org/). 

Considering the overlap with Sustainability goals (outlined in our welcome box and expanded on in this [history post](https://make.wordpress.org/sustainability/2023/09/06/how-the-wordpress-sustainability-team-was-born-during-wordcamp-europe-2023/)), I think we (as a team) should spotlight this project during meetings and see what can do to support WPCC in between.

**Comment by gusaus** [comment]
@courtneyr-dev mentioned [Free and Open Source Software Sustainability Fund](https://www.opentech.fund/funds/free-and-open-source-software-sustainability-fund/) in [Slack](https://wordpress.slack.com/archives/C03JNV77Y57/p1715032148615289) and I wanted to reference my response as it's related to this project (or goal).

> Some of the folks behind that are active in https://slack.opencollective.com/ (channels like #opensource and #sustainoss). Also folks from GitHub currently coordinating https://maintainermonth.github.com/
>
> We've had several discussions in those channels about sustaining WordPress (and other members of the Open Website Alliance [#19](https://github.com/WordPress/sustainability/issues/19)), but without involvement or guidance from leadership we can't really follow through with [#15](https://github.com/WordPress/sustainability/issues/15) and other [related projects](https://github.com/WordPress/sustainability/issues?q=is%3Aissue+is%3Aopen+label%3AEconomic) and goals.
> 
> Seems like we could solve that by [centralizing cross-team collaboration](https://github.com/WordPress/sustainability/discussions/32#discussioncomment-9242354) under a working group that includes leadership and folks already connected and familiar with Open Collective.

Especially if we can help extend Five for the Future by enabling and crediting financial contributions (mentioned in #16).
