### ISSUE TITLE
Refine and extend Five for the Future

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#16]
Last year, @harishankerr [published a blog post](https://make.wordpress.org/project/2023/01/09/request-for-feedback-how-can-we-improve-the-five-for-the-future-contributor-journey/) requesting feedback from contributors on how to improve the contributor journey of WordPress. The post was followed up by a [session on Five for the Future](https://make.wordpress.org/summit/2023/08/24/community-summit-discussion-notes-refining-five-for-the-future-for-a-robust-wordpress-community/) at the recent [WordPress Community Summit](https://communitysummit.wordcamp.org/2023/).

Around the same time the Sustainability Team become official (see [this post](https://make.wordpress.org/sustainability/2023/09/06/how-the-wordpress-sustainability-team-was-born-during-wordcamp-europe-2023/) about the teams formation, purpose, and goals), added this project to the [Sustainability roadmap](https://github.com/orgs/WordPress/projects/134), and started exploring ways to contribute and collaborate.

Then in early 2024, @naokomc posted [this call](https://make.wordpress.org/community/2024/01/12/call-for-mentees-mentors-cohort-2/) for mentees, mentors, and [project ideas](https://github.com/WordPress/wp-contributor-working-group-tracker/discussions/7) for the next [Contributor Mentorship Program](https://make.wordpress.org/community/handbook/contributor-day/contributor-working-group/contributor-mentorship-program-for-wordpress/) Cohort. Sustainability team members answered this call by not only applying to become mentors but collaborating and contributing in related [meetings](https://make.wordpress.org/community/tag/mentorship-chat/), [issues](https://github.com/WordPress/wp-contributor-working-group-tracker/issues), and [discussions](https://github.com/WordPress/wp-contributor-working-group-tracker/discussions). 

Finally @harishankerr posted [this proposal](https://make.wordpress.org/project/2024/01/24/proposal-updates-to-five-for-the-future-from-the-community-summit/) with actionable recommendations based on Community Summit discussions.

## Recommended Action Items
What follows below are recommendations from the aforementioned proposal along with related projects and ideas from Sustainability and other teams.

We'll keep this section updated based on feedback in the proposal, comments in this issue, and related discussions.

### Process Improvement

- Implement the Make/Contributor Tool into contributor recruitment for Five for the Future.
- Establish constant communications with current and new pledgees to help them stay active (automated email check-ins for existing pledges and email onboarding for new pledgees)
- Improve Onboarding Processes for Make/Teams – Identifying and sharing impactful projects for teams, standardizing handbooks, simplifying team handbooks, and onboarding.
- Treat 5ftF Sponsorship like WordCamp sponsorships with similar benefits.

#### Related Projects
- https://github.com/WordPress/sustainability/issues/14 (Community, Training, Documentation, Marketing, and Sustainability teams)
  - Create standardized list of Team roles, skills, and commitments
  - Provide clear/easy entry points for contributing to multiple Teams
  - Provide clear/easy entry points for paid/sponsored contributions

### Sponsorship

- Task-based or project-based contributor sponsorships, companies sponsor contributor time for a certain task or project in a Make/Team.
- Project/release-based contributor sponsorships where companies could sponsor external contributors for a limited time as they work on specific projects.

#### Related projects
- https://github.com/WordPress/sustainability/issues/15 (Contributor Working Group, Community, Training, Documentation, Marketing, and Sustainability teams)
  - https://github.com/WordPress/sustainability/issues/24
  - https://github.com/WordPress/sustainability/issues/22
  - https://github.com/WordPress/sustainability/issues/19
- https://github.com/WordPress/sustainability/issues/10 (Contributor Working Group, Community, Training, Documentation, Marketing, Meta, and Sustainability teams)
  - Create a Marketplace listing companies which provide WordPress-related services, hosting, training, books, and more.
  - Create automated crediting system to recognize the contributions of both individual contributors and their organizational sponsors, and to begin measuring the contribution ecosystem that supports WordPress
    - Recognize individual contributors for their work
    - Recognize organizational sponsors for their contributions
    - Recognize financial contributions
  - Incentive contribution by tying the crediting system to the WordPress services marketplace ranking
  

### Mentorship

- To Provide dedicated mentoring and onboarding for Five for the Future companies and self-sponsored contributors. 
- Helping companies set up contribution teams and onboarding sponsored contributors to Make/Teams
- 1:1 or group mentorship to help self-sponsored contributors onboard effectively.

#### Related projects

- https://github.com/WordPress/sustainability/issues/21 https://github.com/WordPress/sustainability/issues/18 (Community, Training, Documentation, Marketing, and Sustainability teams)
   - Extend the [Contributor Mentorship Program](https://make.wordpress.org/project/tag/mentorship-program/) so that all Teams can onboard and train new contributors.
   - [Create/extend teaching curriculum](https://github.com/WordPress/Learn/issues/527) (see [this comment](https://github.com/WordPress/Learn/issues/527#issuecomment-1881649151) for additional detail/context)
   - Define and document contributor roles
   - Create [learning pathways](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) for each contributor role

## Reference/resources
* [Proposal: Updates to Five for the Future from the Community Summit](https://make.wordpress.org/project/2024/01/24/proposal-updates-to-five-for-the-future-from-the-community-summit/) 
* [Refining Five for the Future For a Robust WordPress Community](https://make.wordpress.org/summit/2023/08/24/community-summit-discussion-notes-refining-five-for-the-future-for-a-robust-wordpress-community/)
* [Request for Feedback: How can we Improve the Five for the Future Contributor Journey?](https://make.wordpress.org/project/2023/01/09/request-for-feedback-how-can-we-improve-the-five-for-the-future-contributor-journey/)

**Comment by gusaus** [comment]
While the issue description isn't compelling (at this point) the comments and discussions referenced should provide context (until a project manager takes this over). I'll also reference this [SustainWP](https://sustainwp.com/) podcast [episode](https://sustainwp.com/podcast/episode-5-wordpress-cms-how-can-we-make-it-more-sustainable/) where several Sustainability Team (reps and members) delve into solving similar problems and solutions.

Ideally we can join up to refine and extend Five for the Future so it enables a larger, more diverse, inclusive community.

**Comment by gusaus** [comment]
Following up on the last comment (after listening to most of the referenced episode). First we should loop in @harishankerr and other Five for the Future leads. Also seems like there are other teams (like [Meta](https://make.wordpress.org/meta/) and [Community](https://make.wordpress.org/community/)) that should be involved (and lead?). 

Also would like to elaborate on some of the references in the description. 

[As noted](https://make.wordpress.org/summit/2023/08/24/community-summit-discussion-notes-refining-five-for-the-future-for-a-robust-wordpress-community/#comment-70070) in the community summit discussion, it's already possible to further the goals of 5ftF by:

> Integrating funding tools into WordPress.org could be a solution as it would provide a centralized way to discover, fund, and receive credit for sponsoring projects, individuals, or even teams. By providing the same fiscal host options as GitHub Sponsors, funding would flow independently of WordPress Foundation, Automattic, or other official org or entity.

> If tied in with an automated crediting system, in-kind and financial sponsors could receive credit (like logos and badges) in a uniform way.

> While this is obviously a non-technical overview, all of this is something the Drupal project and community are currently working on. Not only is making the tools and processes available to other open source projects like WordPress a goal, it’s a priority for the working group we’re part of in Open Collective’s Community.

In the year since the original comment (in a post about [Open Source and how we sustain ourselves](https://make.wordpress.org/project/2022/08/01/open-source-and-the-free-rider-problem/)), there seems to be complimentary projects (like the Dashboard Initiative https://github.com/WordPress/sustainability/issues/10) and more interest in cross-project collaboration and [resource pooling](https://wptavern.com/automattic-donates-e20000-to-fund-next-phase-of-drupal-gutenberg-development) (between projects like WordPress, [Drupal](https://dri.es/balancing-makers-and-takers-to-scale-and-sustain-open-source), [Open Collective](https://github.com/opencollective), [CHAOSS](https://chaoss.community/), and more), it there was stakeholder interest and support to make some much needed improvements, we could make it so!

**Comment by gusaus** [comment]
Circling back here to note @harishankerr just posted the following P2 [Proposal: Updates to Five for the Future from the Community Summit](https://make.wordpress.org/project/2024/01/24/proposal-updates-to-five-for-the-future-from-the-community-summit/)

Haven't had a chance to reconcile with suggestions in this issue, but considering we've been collaborating and submitting [project ideas](https://github.com/WordPress/wp-contributor-working-group-tracker/discussions/7) for the upcoming [Contributor Mentorship Program Cohort](https://make.wordpress.org/community/2024/01/12/call-for-mentees-mentors-cohort-2/), there could be additional source material for collaboration and mentorship project ideas.

**Comment by gusaus** [comment]
Skimming through the P2 proposal and realizing there are several [roadmap items](https://github.com/orgs/WordPress/projects/134) and/or [mentorship project ideas](https://github.com/WordPress/wp-contributor-working-group-tracker/discussions/7) that overlap including the following:

- https://github.com/WordPress/sustainability/issues/14
- https://github.com/WordPress/sustainability/issues/15
- https://github.com/WordPress/sustainability/issues/18
- https://github.com/WordPress/sustainability/issues/22
- https://github.com/WordPress/sustainability/issues/10

**Comment by naokomc** [comment]
I will share my thoughts on our collaboration opportunities based on the Five for the Future project point of view. I distilled them into three questions (the line starting with 💡) – I hope this is helpful! 😄 

## Process Improvement (Onboarding and Mentorship)

Both 5ftF and the Sustainability Team see contributor onboarding and mentorship as priorities. 

### Sustainability
- #18
  - Extend the [Contributor Mentorship Program](https://make.wordpress.org/project/tag/mentorship-program/) so that all Teams can onboard and train new contributors.
- #21

### 5ftF
- To Provide dedicated mentoring and onboarding for Five for the Future companies and self-sponsored contributors. 
- Helping companies set up contribution teams and onboarding sponsored contributors to Make/Teams.
- 1:1 or group mentorship to help self-sponsored contributors onboard effectively.

Enhancing the mentorship program with increased structure and consistency can foster mentorship across the board for both companies and individual contributors. This requires establishing well-defined guidelines, providing resources, and creating support systems to facilitate contributions.

**💡 Would there be interest in joining forces to enhance our onboarding processes and mentoring programs?**

## Sponsorship

### Sustainability
- #15

### 5ftF 

- Task-based or project-based contributor sponsorships, companies sponsor contributor time for a certain task or project in a Make/Team.
- Project/release-based contributor sponsorships where companies could sponsor external contributors for a limited time as they work on specific projects.

We've learned that the Five for the Future companies are often looking for tangible proof or metrics to demonstrate the impact made by their sponsored contributors.

For instance (although this is not a contributor sponsorship example), numerous companies have sponsored WordCamps worldwide, directing their funds toward the events. This demonstrates that companies recognize the value in financially supporting a project where they can gain visibility as sponsors and directly observe the outcomes of their contributions.

 **💡 Can we collaborate on figuring out a sponsorship model that can sustainably benefit the project and the companies & contributors in the ecosystem?**

## Visualization (Dashboard)

## Sponsorship

### Sustainability
- #10

### 5ftF
- Create team health dashboards for all Make/Teams, which help contributors identify impactful projects and areas that need help ([Already underway](https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/)).

**💡 How about we collaborate on researching/defining the Dashboard elements that can indicate the project's sustainability?**

**Comment by gusaus** [comment]
@naokomc really appreciate you taking the time to associate 5ftF goals with overlapping roadmap projects! 

From my perspective (as a team/community member interested in all the areas being outlined) we're already collaborating/contributing as individuals, but we don't yet have the [structure](https://github.com/WordPress/sustainability/issues/4) or [capacity](https://github.com/WordPress/sustainability/issues/2) to contribute as a team.

However if all the overlapping projects we're identifying here were owned and/or managed by members of the  [Contributor Working Group](https://make.wordpress.org/community/handbook/contributor-day/contributor-working-group/) (that consists of mentors, reps, and facilitators from multiple teams) we'd be able to solve both problems as goals/outcomes would benefit this (and every team).

Does that make sense?

**Comment by naokomc** [comment]
Very true, we're already collaborating as individuals but that's separate from team collaboration.
If structure or capacity are blockers, it might be most effective to keep the current way where we all stay involved in projects and initiatives as we can.

The Contributor Working Group is currently focusing on the mentorship program only. I'm sure many are also interested in the areas I mentioned in the above comment, but the management of the Five for the Future program is mainly done through this [GitHub repository](https://github.com/WordPress/five-for-the-future/).

One thing we can start doing is incorporating what's happening with the Five for the Future project and Sustainability Team (in the area of contributor sustainability) to the regular Contributor Working Group meetings.

**Comment by gusaus** [comment]
> The Contributor Working Group is currently focusing on the mentorship program only.

Apologies for misunderstanding. My assumptions were based on the following clarifications in the [Recap of the Contributor Working Group’s Mentorship Chat on December 21, 2023](https://make.wordpress.org/community/2023/12/28/recap-of-the-contributor-working-groups-mentorship-chat-on-december-21-2023/) (and related discussions) was that both programs are owned/managed by the Contributor Working Group.

> **Five for the Future** 
> Starting in the new year, our group will start looking at the Five for the Future program as well. Group members are encouraged to share their feedback on the program in the [Five for the Future GitHub Repository](https://github.com/WordPress/five-for-the-future/issues). Folks can create  documentation for the 5ftF contributors, please add it to[ the GH repository](https://github.com/WordPress/five-for-the-future/issues). You can also review existing issues and share any feedback as required too.

If yes, I think all the projects referenced (and probably some other [roadmap ideas](https://github.com/WordPress/sustainability/labels/project) overlap with goals and needs of either/both programs.

Does that make sense?

**Comment by naokomc** [comment]
I also hope the Five for the Future program will receive more focus and resources from the Contributor Working Group members. But realistically speaking, I expect the groups' meetings & activities will mostly be about the mentorship program until the 2nd cohort concludes (some group members are also applying as mentors and/or have dedicated tasks for the 6.5 release). I will try to bring more 5ftF topics & updates to the Working Group meetings, though! Through GitHub, anyone can contribute at any time too.

**Comment by gusaus** [comment]
>  I expect the groups' meetings & activities will mostly be about the mentorship program until the 2nd cohort concludes (some group members are also applying as mentors and/or have dedicated tasks for the 6.5 release).

Thanks for clarifying the priorities, timing, and providing more info on ownership/management in [this related thread](https://wordpress.slack.com/archives/C03JNV77Y57/p1706160636603379) (I'll paste the comment below to centralize) 

> There are 10 admin users on the Five for the Future website, including Hari, myself, and some others from the Meta + Core Teams and the leadership.
>
> Currently Hari and I contributing to administrating the site, and we are tying to get feedback from 5ftF company reps and Contributor Working Groups.
>
> It can be extended, of course, as more active contributors start taking on admin tasks/responsibilities, or working on the site functionality.

Taking this all into consideration it seems like most (if not all) of the overlapping projects/goals identified in https://github.com/WordPress/sustainability/issues/16#issuecomment-1911677470 could move forward as [Mentorship projects](https://github.com/WordPress/wp-contributor-working-group-tracker/discussions/7) if they were broken out into smaller components https://github.com/WordPress/wp-contributor-working-group-tracker/discussions/7#discussioncomment-8313547 and resourced (mentors, admins, and other contributors from multiple teams).

**Comment by gusaus** [comment]
Circling back to this goal/priority:

> Create team health dashboards for all Make/Teams, which help contributors identify impactful projects and areas that need help ([Already underway](https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/)).

It's hard to tell what the status is (or where/how to contribute). Either way, if you skim through some of the comments, you'll see what inspired some of the related goals in the issue description (along with some paths for collaboration and resource pooling with Drupal and other open source projects and contributors in the Open Collective ecosystem.

https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/#comment-398
https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/#comment-399

**Comment by gusaus** [comment]
Still a work in progress but I think [the description](https://github.com/WordPress/sustainability/issues/16#issue-1991357835) provides a high level view of the program, recommendations for fixing/improving, and an overview of overlapping goals and projects.

**Comment by gusaus** [comment]
Coming out of another successful mentorship cohort, it looks like the Contributor Working Group is focusing back on Five for the Future (see [this discussion](https://github.com/WordPress/wp-contributor-working-group-tracker/discussions/11) in the Contributor Working Group repo). 

As @naokomc mentioned above https://github.com/WordPress/sustainability/issues/16#issuecomment-1913966275, it looks like collaboration  is centered in https://github.com/WordPress/five-for-the-future/

That being the case, I'm wondering if we could/should:

- transfer this issue to https://github.com/WordPress/five-for-the-future
- convert this into a discussion
- make sure ideas, features, related projects are logged/referenced in https://github.com/WordPress/five-for-the-future/issues
- determine which (public) channel would be best for centralize cross-team collaboration in Slack

Would be great if @naokomc and/or @harishankerr could weigh in so all interested contributors could join forces to improve and extend the future!
