### ISSUE TITLE
Leverage and contribute to the Open Website Alliance

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#19]
Edit: Updated to reflect the following https://www.drupal.org/association/blog/drupal-association-co-founds-the-open-website-alliance

### About the Open Website Alliance 
The international community organizations behind Drupal, Joomla, TYPO3, and WordPress join forces in a leadership-level alliance. The members of the Alliance are united in their shared values and their message to decision-makers to always choose open source software over proprietary systems.

The Alliance represents the content management systems (CMS) behind roughly 50% of all websites online today. The Open Website Alliance was founded to promote the choice of open-source software and facilitate collaboration between free and open-source web content management projects, furthering openness, trust, and quality. Other free and open-source CMS organizations are encouraged to apply for membership.

**Collaboration on Leadership Level**
The Alliance comes about as the result of the collaboration between the [Drupal Association](https://www.drupal.org/association), [Open Source Matters (Joomla)](https://www.opensourcematters.org/), the [TYPO3 Association](https://typo3.org/), and the [WordPress Project](https://wordpress.org/) around an [open letter to the European Union](https://typo3.org/project/press/press-releases/open-letter-to-eu-legislators).

The Alliance uniquely connects its members on a leadership level. This means the organizations can more easily coordinate strategy and actions, fostering new cross-community collaboration projects and strengthening those that already exist.

### Collaboration and contribution opportunities
This new alliance could help enable additional opportunities for these projects to collaborate, pool resources, grow and make meaningful change in the open source landscape. 
 
* https://github.com/WordPress/sustainability/issues/22 - Coordinate and participate in Fundraising events to generate resources for current/future priorities and exposure for each project and community.
* https://github.com/WordPress/sustainability/issues/18 - Share ideas, open source tools, best practices, and other resources that will sustain and grow each project while creating new opportunities for contributors across all projects.
* https://github.com/WordPress/sustainability/issues/24 - Use Open Collective's fiscal sponsorship service + open source tools to pool and distribute funds between priority projects and programs.  
* more ideas to follow based on additional input and feedback...

### Updates/next steps
* Nov 23 - @meeware reached out to Josepha to ask how the process had gone so far with the CRA legislation, and will be coming back to this issue with a clarified narrative on the process in this case, and additional feedback and potential actions for the team to undertake.
* Feb 24 - Open Website Alliance announced
 
### Reference/resources
* [Open Source participation in global legislation](https://make.wordpress.org/summit/2023/09/04/community-summit-discussion-notes-open-source-participation-in-global-legislation/) (Community Summit discussion)
* [Drupal Association Co-Founds the Open Website Alliance](https://www.drupal.org/association/blog/drupal-association-co-founds-the-open-website-alliance) (drupal.org)

**Comment by gusaus** [comment]
@meeware As the newest lead/admin of [FundOSS](https://opencollective.com/fundoss) (referenced in https://github.com/WordPress/sustainability/issues/15) I feel like we'll be able to follow though with this action item 

> Coordinate and participate in Fundraising events to generate resources and exposure for the legislation and projects involved.

Especially if Josepha and other community leaders are involved!

**Comment by nickchomey** [comment]
I strongly recommend the folks in the Open Website Alliance get in touch and collaborate with the folks at the other OWA - Open Web Advocacy. They have been instrumental in making the EU's DMA come into existence, and are leading the fight against Apple's various efforts to kill the Web entirely.

https://open-web-advocacy.org/apple-attempts-killing-webapps/

It would be great if the members of the OWAlliance can put their voice and weight behind the effort, in order to not just save the Web, but make it flourish once again.

**Comment by gusaus** [comment]
Not sure if folks behind the alliance have clarified how contributors/community members of participating projects can become involved. Looks like contributing to https://openwebsitealliance.org/ could be one way!
