### ISSUE TITLE
Determine team roles, responsibilities, commitments, and resource needs

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#2]
## Roles/responsibilities/commitments
In addition to team reps, we need to determine other roles, responsibilities, commitments, and resources needed to sustain our team. The roles below were initially compiled from our [channel Canvas](https://wordpress.slack.com/canvas/C03JNV77Y57?focus_section_id=temp:C:VFNeea147b218e54376ae2ea3b57), [Community Summit notes](https://make.wordpress.org/summit/2023/09/06/community-summit-discussion-notes-iterating-on-the-team-rep-role/), and meeting notes/discussions on https://make.wordpress.org/sustainability/ and in Slack. 

I then consulted with my friend ChatGPT about generating a list of WordPress community contributor roles (along with a description, required skills, and average weekly time commitment).

Below is a curated list of AI generated roles that seem best suited for our Team. Obviously we need knowledgable humans to help augment and refine in the comments. 

If there's not yet a master list of community contributor roles residing somewhere on https://make.wordpress.org/, possibly this can be the start of another project we can contribute to!?!

### Team Rep/Community Liaison
- Description: Team Reps/Community liaisons act as a bridge between the WordPress community and the WordPress project leadership, facilitating communication and collaboration.
- Required Skills: Strong communication and diplomacy skills, a deep understanding of the WordPress community, and the ability to mediate discussions.
- Average Weekly Time Commitment: 2-5 hours

### Documentation Writer
- Description: Documentation writers create and update documentation for WordPress, including user guides, developer resources, and code reference materials.
- Required Skills: Strong writing and communication skills, technical knowledge of WordPress, and the ability to create well-structured documentation.
- Average Weekly Time Commitment: 2-5 hours

### Team Meeting Coordinator
- Description: Team meeting coordinators organize and facilitate regular team meetings, ensuring effective communication and collaboration among team members.
- Required Skills: Meeting facilitation, communication skills, and the ability to maintain meeting agendas and records.
- Average Weekly Time Commitment: 2-5 hours

### Project Manager
- Description: Project managers oversee specific WordPress community projects, coordinate team activities, set timelines, and ensure project goals are met.
- Required Skills: Project management expertise, organizational skills, and the ability to collaborate with cross-functional teams.
- Average Weekly Time Commitment: 2-5 hours

### Marketing Contributor
- Description: Marketing contributors help promote WordPress through content creation, social media management, and marketing campaigns.
- Required Skills: Marketing knowledge, content creation skills, social media expertise, and a strong understanding of WordPress.
- Average Weekly Time Commitment: 2-5 hours

### DEIB Liaison
- Description: DEIB Liaisons serve as a bridge between the DEIB team and other WordPress teams or committees, ensuring DEIB principles are integrated into various aspects of the community.
- Required Skills: Communication, collaboration, and the ability to facilitate cross-team discussions.
- Average Weekly Time Commitment: 2-5 hours

### Community Fundraising Coordinator
- Description: Community fundraising coordinators lead efforts to secure sponsorships, grants, and donations to support WordPress community events and initiatives. They work closely with event organizers and teams to ensure adequate funding and financial sustainability.
- Required Skills: Fundraising expertise, sponsorship negotiation, grant writing, financial management, and strong communication skills.
- Average Weekly Time Commitment: 2-5 hours

### Training Contributor
- Description: Training contributors develop educational materials, courses, and workshops to help users and developers learn how to use and contribute to WordPress effectively.
- Required Skills: Teaching and instructional design skills, expertise in WordPress, and content creation abilities.
- Average Weekly Time Commitment: 2-5 hours

### Mentorship Coordinator
- Description: Mentorship coordinators facilitate mentorship programs within the WordPress community, matching experienced contributors with newcomers and overseeing their progress.
- Required Skills: Strong communication, organizational skills, and the ability to provide guidance and support.
- Average Weekly Time Commitment: 2-5 hours

## Resource Needs
In order to handle the expanded scope, we'll need a mix of the following:

### Contributors
* Sponsored contributors
* New contributors (volunteer)
* Experienced contributors (paid and/or volunteer)

### Funds
We should explore and experiment with the following options:
* [Open Collective](https://opencollective.com/)
* [GitHub Sponsors](https://github.com/sponsors) 

### Related Community Summit links
Certain aspects/outcomes of the following [Community Summit discussions](https://make.wordpress.org/summit/) _most likely_ will address common goals and needs.
- [Iterating on the Team Rep role](https://make.wordpress.org/summit/2023/09/06/community-summit-discussion-notes-iterating-on-the-team-rep-role/)
- [Understanding contributor leadership roles in the WordPress open source project](https://make.wordpress.org/summit/2023/09/01/understanding-contributor-leadership-roles-in-the-wordpress-open-source-project/)
- [Communication and Collaboration – Finding Your Way Around WordPress](https://make.wordpress.org/summit/2023/09/03/community-summit-discussion-notes-communication-and-collaboration-finding-your-way-around-wordpress/)
- [Refreshing the contributor pipeline](https://make.wordpress.org/summit/2023/08/27/community-summit-discussion-notes-refreshing-the-contributor-pipeline/)
- [Refining Five for the Future For a Robust WordPress Community](https://make.wordpress.org/summit/2023/08/24/community-summit-discussion-notes-refining-five-for-the-future-for-a-robust-wordpress-community/)
- [Diversity, Equity, Inclusion, and Belonging (DEIB) for all Make Teams](https://make.wordpress.org/summit/2023/08/27/community-summit-discussion-notes-diversity-equity-inclusion-and-belonging-deib-for-all-make-teams/)

**Comment by gusaus** [comment]
So a couple additional notes and thoughts about the AI generated roles. 

First off, the Team Rep was 'not' a role that Chat GPT generated. The description and key responsibilities of Community Liaison role however looked very similar to those of a Team Rep. So I just modified the title. 

The Documentation Writer and Team Meeting Coordinator roles (again AI generated and need human refinement) would essentially alleviate the Team Rep(s) from having to run the meetings and post updates themselves. Team Reps would be responsible until other contributors came aboard. If there are three or more team reps, each could divvy up specific responsibilities based on interest and the amount of time they're able to commit. 

Either way, it seems like some combo of the first three roles would be considered essential for the Team to exist.

Curious to hear input from those with more Team and WP Community experience.

**Comment by gusaus** [comment]
I scaled back the Average Weekly Time Commitment for each role to 2-5 hours. Of course the number of team reps and whether they are sponsored will affect availability. We'll have a clearer picture after the [nomination and voting process](https://make.wordpress.org/sustainability/2023/09/15/call-for-wordpress-sustainability-team-representatives/) is complete.

The fact that we'll be collaborating with multiple Teams and Working Groups on [projects](https://github.com/orgs/WordPress/projects/134) could create opportunities to share team members and consolidate roles. So if a contributor is sponsored or funded, they could potentially make a part or full-time job as a specialist that works across multiple teams and projects.

**Comment by gusaus** [comment]
Realizing no DEIB roles were included in the initial rounds, I asked ChatGPT to list some roles for a Diversity, Equity, Inclusion, and Belonging (“DEIB”) team. While it created several, I included one (DEIB Liaison) that seemed to make the most sense (even before human refinement).

**Comment by sereedmedia** [comment]
While this all makes sense, currently existing team roles that are defined project-wide are: 

- Team Rep
- Team Member
- Contributor

To get started, the Sustainability team needs to define our criteria for those roles. 

There is currently no structure within Make WordPress for additional team role delineation. The topic of expanding team roles and how teams are structured was discussed extensively at the Community Summit (related links below). A change in structure of that nature has to come from within the community before we can adopt a different team structure, or it won't be sustainable (no pun intended).

I do think we, as the Sustainability team, could be the home for that discussion.

## Related Community Summit links
_Note: I haven't yet read these summaries but I was present and participated in the discussion._

- [Iterating on the Team Rep role](https://make.wordpress.org/summit/2023/09/06/community-summit-discussion-notes-iterating-on-the-team-rep-role/)
- [Understanding contributor leadership roles in the WordPress open source project](https://make.wordpress.org/summit/2023/09/01/understanding-contributor-leadership-roles-in-the-wordpress-open-source-project/)

**Comment by gusaus** [comment]
Totally agree we shouldn't get ourselves bogged down by titles (outside of the official, generic, project-wide roles). We should probably start with the required "Team Rep" role and divvy up required responsibilities between [nominees](https://poll.fm/12838532) (assuming everybody is interested in making an ongoing commitment regardless if they get voted in) and others already pledging time to our team!!

> [39 people](https://make.wordpress.org/sustainability/pledges/) have pledged time to contribute to Sustainability Team efforts!

Seems like [improving the current pledging system](https://make.wordpress.org/project/2023/09/25/request-for-feedback-make-team-dashboards/#comment-399) could be another activity for interested team members!

**Comment by YellowlimeNL** [comment]
My suggestion would be that once the [team rep voting](https://make.wordpress.org/sustainability/2023/10/25/voting-for-makewp-sustainability-team-representatives-2024/) has ended (9th of november 2023, 01.00 CET), and team Reps are known. They have a meeting to discuss the roles internally and share outcomes within 2 weeks time. Knowing that the WP Sustainability Team will have 4 team reps, it makes no sense to me personally to have 4 people with identical roles. 

Once roles of each team rep is clear internally and published as P2. We can move forward making clear which collaborators and team reps will work on the various topic (ecological, social, economical) based on personal interest, capacities, motivation etc and start working on items/issues per topic.

These are just my personal thoughts.

**Comment by YellowlimeNL** [comment]
> While this all makes sense, currently existing team roles that are defined project-wide are:
> 
>     * Team Rep
> 
>     * Team Member
> 
>     * Contributor
> 
>     * [Iterating on the Team Rep role](https://make.wordpress.org/summit/2023/09/06/community-summit-discussion-notes-iterating-on-the-team-rep-role/)
> 
>     * [Understanding contributor leadership roles in the WordPress open source project](https://make.wordpress.org/summit/2023/09/01/understanding-contributor-leadership-roles-in-the-wordpress-open-source-project/)

What is the common difference between Team Member and Contributor @sereedmedia? Contributors are the ones that [pledged time](https://make.wordpress.org/sustainability/pledges/)?

**Comment by YellowlimeNL** [comment]
As metioned at [Slack](https://wordpress.slack.com/archives/C03JNV77Y57/p1699014431670779?thread_ts=1699013047.647549&cid=C03JNV77Y57) by @Nahuai, "in one hand there are the Team reps responsible for team management (and more) and them it could be project leaders that could move forward specific tasks.
The Hosting Team use that approach as mentioned on their handbook."
https://make.wordpress.org/hosting/handbook/get-involved/team-reps/

**Comment by YellowlimeNL** [comment]
That brings us to 4 'potential' roles for the WP sustainability team:

- Team Rep
- Project Leaders (one per topic: ecological, economical, social)
- Team Member
- Contributor

With some doubt left about the difference between Team Member and Contributor.

**Comment by gusaus** [comment]
First off - I'm really glad there's been some focus on this task during the past few meetings. 

As mentioned in the description https://github.com/WordPress/sustainability/issues/2#issue-1916229765 my friend ChatGPT helped generate the initial list of WordPress community contributor roles (along with a description, required skills, and average weekly time commitment). I then went back and refined and generated/added some additional ones (see subsequent comments for explanations).

This was meant to provide us with a starting point for contributors interested in claiming and customizing their own roles (and commitments).

Personally (especially after realizing how little structure and standardization there is from team to team), I'd recommend anyone interested just comment about any roles they'd like to take on. Also suggest ones that aren't listed or make suggestions to how existing ones could be improved.

Thoughts?

**Comment by gusaus** [comment]
Looking at these roles (after several more weeks of observing and interacting in the community) it seems like several (most?) teams could have similar roles. If we make creating and documenting a master list of roles, responsibilities, and commitments a roadmap project https://github.com/WordPress/sustainability/issues/14 (assuming this doesn't already exist), we'd be creating opportunities for newcomers to gain experience (and potentially create a career) by contributing to multiple teams.  

Similar case for experienced contributors (if we move this roadmap idea forward #15).

**Comment by nahuai** [comment]
I quite agree with the 4 roles mentioned but also have some doubts about the difference between "Team Member" and "Contributor". If anyone has a clear view about it please share it.

**Comment by YellowlimeNL** [comment]
Actually I see 2 options for now, knowing we have almost formally 4 team reps:

1. We first formalize the team and describe roles/functions and responsibilities. Before we start with picking up [issues](https://github.com/WordPress/sustainability/issues).
2. We start with the [issues](https://github.com/WordPress/sustainability/issues) and then see in a natural, organical way who's involved, has interest in issues/projects, those people can pick up a formal role/function later on.

Any thoughts on this?

**Comment by nahuai** [comment]
Also, once we decided the roles (and it's descriptions) it would be nice to create something similar to what the Hosting Team added to their Handbook: https://make.wordpress.org/hosting/handbook/get-involved/team-reps/

**Comment by meeware** [comment]
I propose that we have an overall rep, and 3 focus reps. For now that structure will allow us to have an owner to prioritisation within the 3 focus areas, and leave 1 rep left over to be overall coordinator. Not a seniority thing, but more coordinator. This might not be 'standard' but it does seem a good way to cluster responsibility at this stage of the team's evolution.

Working with them would be team members and coordinators.

I anticipate that team to team liaison (between Sus and community, or sus and performance for example) would emerge from the focus area priorities.

**Comment by YellowlimeNL** [comment]
> I propose that we have an overall rep, and 3 focus reps. For now that structure will allow us to have an owner to prioritisation within the 3 focus areas, and leave 1 rep left over to be overall coordinator. Not a seniority thing, but more coordinator. This might not be 'standard' but it does seem a good way to cluster responsibility at this stage of the team's evolution.

Does this imply that the 3 focus reps do also have the job of project (Enviornmentaly, Social, Economical) lead or do you suggest to have seperate people acting as Team Rep and Project Lead?

**Comment by noraferreiros** [comment]
I just want to bring a reminder: Team Reps not necessary have to be project leaders. Team Reps have some responsibilities (bureaucratic and logistical, mainly) they have to combine with contributing. Being an overall lead to coordinate 3 project areas and fulfill Team Rep regular tasks is quite a lot of work.

**Comment by meeware** [comment]
> Does this imply that the 3 focus reps do also have the job of project (Enviornmentaly, Social, Economical) lead or do you suggest to have seperate people acting as Team Rep and Project Lead?


I suggest that for the moment it would be acceptable to have the focus rep individuals also hold the project roles for the 3 areas. It could be in their individual remit to delegate project management to another team member or contributor, and to consult with the team on these meetings to confirm that delegation.

While there are only a few people here for now, I anticipate that with the clear structure that's emerging, we'll soon have a stability and focus that encourages more regular members, and we can have that delegation within a few weeks.

**Comment by YellowlimeNL** [comment]
> > Does this imply that the 3 focus reps do also have the job of project (Enviornmentaly, Social, Economical) lead or do you suggest to have seperate people acting as Team Rep and Project Lead?
> 
> I suggest that for the moment it would be acceptable to have the focus rep individuals also hold the project roles for the 3 areas. It could be in their individual remit to delegate project management to another team member or contributor, and to consult with the team on these meetings to confirm that delegation.
> 
> While there are only a few people here for now, I anticipate that with the clear structure that's emerging, we'll soon have a stability and focus that encourages more regular members, and we can have that delegation within a few weeks.

I consider this a third option, besides the 2 options mentioned here https://github.com/WordPress/sustainability/issues/2#issuecomment-1805642638
