### ISSUE TITLE
Extend the do_action hackathon format

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#21]
[do_action](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon/) hackathons are community-organized events that focus on using WordPress to give deserving charitable organizations their own online presence. Each do_action event includes participants from the local WordPress community coming together to plan and build brand new websites for a number of local organizations in one day.

The goal of do_action is to support these charitable organizations by giving them a fresh and dynamic online presence. This enables them to get on with the work that they already do so well without basic website management getting in the way of their productivity.

### Extending the format
We'd like to extend by Including opportunities for new contributors and maintainers to receive hands-on training during the entire web development process and thereafter.

* project based mentoring and training opportunities for new contributors
* more flexibility in terms of the format and length of time
    * mix of virtual and in-person events
    * a series of events (as opposed to a one day event)
* more flexibility in terms of the type of participant
    * multiple impact areas (open source, education, mutual aid, civic tech, climate, arts & culture, music, publishing, and more)
    * nonprofit organizations
    * groups and individuals if they have a fiscal sponsor like:
        * [Open Collective Foundation](https://opencollective.com/foundation)
        * [Open Source Collective](https://opencollective.com/opensource)

### Sustainability
Partner with an independent organization/collective to provide the following for contributors and participants
* Enable ways for experienced organizers, mentors, and other key contributors to get paid.
* Provide placement opportunities for trainees.
* Provide nonprofits and other participants ongoing support options.

## do_action Event Ideas
Hackathons and fundraisers focusing on enabling organizations and contributors in specific interest areas or industry groups including:

* do_action for Publishers
* do_action for Broadcasters and Streamers
* do_action for Creative Arts and Music
* do_action for Jazz (organizations, broadcasters, musicians, etc.)

Narrow focus by leveraging/extending a specific set of plugins and themes (like [Newspack](https://github.com/Automattic/newspack-plugin?tab=readme-ov-file#newspack)) and create/curate targeted learning resources.   

### Initial proposal
- [x]  Have Community Team members review and provide feedback on questions and suggestions revolving around extending the do_action event format
  - [x] [WordPress Sustainability Team: NextGen and other Event ideas and suggestions](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.6mqas28j12lq) (Google doc)
  - [x] [Sustainability Team: NextGen and other Event ideas and suggestions](https://wordpress.slack.com/docs/T024MFP4J/F05SUHSBWGZ) (Slack Canvas)
- [x] Submit as a NextGen Event (via the application referenced in [this post](https://make.wordpress.org/community/2023/08/30/the-nextgen-event-project-your-ideas-your-wordpress-community/))
- [ ] Address any questions/concerns about the proposal
- [ ] Work with Community, Training, and other teams to refine during the planning stage

### Planning and implementation
- [ ] Break out into different projects/teams
  - [ ] Improve and extend existing guides and documentation / [Community](https://make.wordpress.org/community/)
    - [ ] [Organizer guide](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon)
    - [ ] [Participant Guide](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon/getting-particpants/participants-guide/#structure-of-the-day)
  - [ ] https://github.com/WordPress/Learn/issues/527 / [Training](https://make.wordpress.org/training/)
    - [ ] Create/extend teaching curriculum for different [teams/groups/audiences](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.cxws8ublx2ux)
    - [ ] Define and document contributor roles
    - [ ] Create [learning pathways](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) for each [contributor role](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#heading=h.po23kwkpbae0)
  - [ ] Extend the current [Contributor Mentorship program](https://make.wordpress.org/community/tag/mentorship-program/) to include mentoring for all contributor roles / [Contributor Working Group](https://make.wordpress.org/community/tag/wpcontributors/)
  - [ ] Improve how do_action uses Open Collective / [Sustainability](https://make.wordpress.org/sustainability/)
    - [ ] [Processes for managing event finances](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon/managing-event-finances/) 
    - [ ] #24 Platform improvements and integrations
- [ ] Determine roles/resources needed to move forward and sustain
   - [ ] [Team structure](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#heading=h.po23kwkpbae0)
   - [ ] Funding
 - [ ] Create fundraising proposal
 - [ ] Secure funds
    - [ ]  #22 - Participate in FundOSS and related fundraisers
    - [x] #15

**Comment by gusaus** [comment]
Realizing this project/issue is on the agenda for the next Training team meeting https://github.com/WordPress/Learn/issues/2048, I've been outlining some more [ideas and questions](https://wordpress.slack.com/docs/T024MFP4J/F05SUHSBWGZ?focus_section_id=temp:C:QaO0e4b4b6adb3c44459e9dc1881) in the [Sustainability Team: NextGen and other Event ideas and suggestions](https://wordpress.slack.com/docs/T024MFP4J/F05SUHSBWGZ) (Slack Canvas).

I'm going to try and attend in real time so I can reference some of those ideas and ask followup questions.

**Comment by gusaus** [comment]
Here's the related Training team [meeting log](https://wordpress.slack.com/archives/C02RW657Q/p1701759707186139), [thread](https://wordpress.slack.com/archives/C02RW657Q/p1701760359625459), and [meeting recap](https://make.wordpress.org/training/2023/12/12/training-team-meeting-recap-5th-december-2023/). Seems like folks are warm to the idea but I'm not quite sure how to proceed beyond asking the following questions and adding some [additional detail](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.3asyf0sbtdcu) to the [WordPress Sustainability Team: NextGen and other Event ideas and suggestions](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit?usp=sharing) (Google doc) we've already shared with the Community Team:

- Could [learning pathways](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress) be created for each project role?
- Are there resources on https://learn.wordpress.org/?
- How can we collaborate/contribute/extend the current [Contributor Mentorship program](https://make.wordpress.org/community/tag/mentorship-program/) to include mentoring at contribution events and hackathons?
  - We’ve been having some discussion with @harishankerr and other community members in recent mentorship chats ([for example](https://make.wordpress.org/community/2023/11/24/recap-of-contributor-working-groups-mentorship-chat-on-november-16th-2023/))
- Are there learn/training resources for mentors (mentoring the mentors)?

**Comment by gusaus** [comment]
After submitting FundOSS https://github.com/WordPress/sustainability/issues/22#issuecomment-1843764018 @hellojuliarose recommended bringing folks together for an event that is less focused on fundraising, and more centered around learning, networking, and/or contributing together. 

While I think the fundraising component is essential (will work on providing clarity in the FundOSS proposal), I went ahead and submitted  a variation of what we've outlined in [this section](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.3asyf0sbtdcu) as a Next Gen event

And about an hour later, received a very positive reply (here's an excerpt)!

> The concept sounds great, and as a next step it would be helpful if you can provide more specifics about the event that you plan to organize, so we can understand how to best support you:

> WordPress Event Proposal: 
> 
> - Event city and country:
> - Is this event in-person, online, or hybrid?
> - If in-person: If you have a potential venue, possibly donated, please share the URL:
> - If online: What platform(s) will you use for this event?
> - Number of attendees/participants (approximately):
> - If you have co-organizers, please share their WordPress.org username:

I'll try to work some of these questions into the google doc. Also will async surface this and related projects at the next Sustainability meeting. Hoping others more well versed in everything from creating event formats to organizing them will find this interesting enough to join the effort!

**Comment by kaitohm** [comment]
I'm a bit late to the discussion here. But I wanted to raise, the Training Team has had an idea to create resources for do_action events for some time. We've never been able to prioritize it as a team, though, or find content creators available to build this out. You can see our GitHub issue for this here: https://github.com/WordPress/Learn/issues/527

> Could [learning pathways](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress) be created for each project role?

Could you share more about what roles this would include?

> Are there resources on https://learn.wordpress.org/?

Not do_action specific. But there are Tutorials and Online Workshop recordings that walk users through creating a site, so these could be used as the teaching aid in learning settings.

What resources would you be looking for specifically? Adding your comments to the GitHub issue above would be the best way to record this need in the Training Team's GitHub repository, too 🙂

**Comment by gusaus** [comment]
@bsanevans Thanks so much for your input (and [surfacing my comments](https://wordpress.slack.com/archives/C02RW657Q/p1701321960164529?thread_ts=1701157449.829559&cid=C02RW657Q) in the Nov 28 Training team meeting  https://github.com/WordPress/Learn/issues/2021)!

And thanks for referencing https://github.com/WordPress/Learn/issues/527 as it was something I stumbled across during related conversations with @courtneyr-dev and other Training and Community team members (in [WordPress](https://wordpress.slack.com/archives/C02RW657Q/p1653374312281729) and [Open Collective](https://opencollective.slack.com/archives/C6YV7NWEM/p1643151854006000) Slack) before the creation of [Sustainability Team](https://sustainwp.com/podcast/episode-7-wordpress-sustainability-team/) gave me a good reason to become more active.

> Could you share more about what roles this would include (for learning pathways)?

At minimum I think for existing build team roles (as defined in the [do_action organizer guide](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon/getting-particpants/#participant-roles)), but we're trying to determine ([in this section of our proposal](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.cxws8ublx2ux)) if/how our extended format (and plan to sustain) will create opportunities to create (and contribute to) additional pathways.

> What resources would you be looking for specifically?

Seems like the suggestions in https://github.com/WordPress/Learn/issues/527 would be more realistic (with our extended/hybrid format). Especially if we narrow our focus initially (see the 'event ideas' in the issue description).

**Comment by gusaus** [comment]
@bsanevans Realizing that additional contributors and resources would most likely be required, we're trying to get Community team/leadership buy-in on this fundraising event format https://github.com/WordPress/sustainability/issues/22

As noted in the issue and proposal there should also be some tie-ins with training and mentoring.

**Comment by kaitohm** [comment]
Thanks for the clarifications here. I see there are a few thoughts regarding the Training Team here.

1. https://github.com/WordPress/Learn/issues/527 is an idea to create a teaching curriculum to be used during a do_action event
2. There's an idea to create learning pathways for different project roles - getting them prepared to run events
3. There's an idea for the Training Team to participate in a mentoring and coordinating capacity (from [the shared document](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#heading=h.po23kwkpbae0))

For point 1, the beginner user learning pathway currently being developed might be good curriculum to use during a do_action. The estimated date of completion for this is July 2024.

Regarding 2, Training has previously helped other teams create content and publish it on Learn. We generally haven't created the content itself, but been available to help with getting content reviewed and published as Sensei content types. How does that align with the expectations of this project?

And finally, 3 sounds like an exciting prospect. The team ran our pilot Course Cohort program in 2023, and we intend to continue that format in 2024. Using the curriculum made in point 2 above, the team would probably be able to assist with running cohort training sessions.

I'll raise this all again in mid-January when the Training Team sets its goals for 2024 to keep it on the team's radar 👍

**Comment by gusaus** [comment]
@bsanevans Thanks again for your input. 

Considering everything related to learning/training we've been talking about here (multiple audiences, learning 'series', learning pathways, mentoring, etc.) is referenced in https://github.com/WordPress/Learn/issues/527, should we centralize our discussion in that issue (as you suggested above)?

I did want to reference @harishankerr's [Recap of the Contributor Working Group’s Mentorship Chat on December 21, 2023](https://make.wordpress.org/community/2023/12/28/recap-of-the-contributor-working-groups-mentorship-chat-on-december-21-2023/), as we touched on some of the same topics and there seems to be a good bit of overlap and mutual interest in collaboration.

**Comment by gusaus** [comment]
I updated the [issue description](https://github.com/WordPress/sustainability/issues/21#issue-2015552917) to reference related projects along with the teams and working groups that own or drive those efforts (also pasted below). 

As is the case with several projects on the [roadmap](https://github.com/orgs/WordPress/projects/134), the Sustainability Team (or team members) will help enable, sustain, and contribute, but not necessarily  'own' them.

Does this seem like a reasonable breakdown of the major components (and teams)? How do we involve leads/owners/managers of projects/programs not owned by Sustainability?

- [ ] Break out into different projects/teams
  - [ ] Improve and extend existing guides and documentation / [Community](https://make.wordpress.org/community/)
    - [ ] [Organizer guide](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon)
    - [ ] [Participant Guide](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon/getting-particpants/participants-guide/#structure-of-the-day)
  - [ ] https://github.com/WordPress/Learn/issues/527 / [Training](https://make.wordpress.org/training/)
    - [ ] Create/extend teaching curriculum for different [teams/groups/audiences](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#bookmark=id.cxws8ublx2ux)
    - [ ] Define and document contributor roles
    - [ ] Create [learning pathways](https://make.wordpress.org/training/2023/07/07/project-thread-learning-pathways-on-learn-wordpress/) for each [contributor role](https://docs.google.com/document/d/1CtVJZdx1oNer9FeCIROlx-IiVh1XkrDKuycdR75phfs/edit#heading=h.po23kwkpbae0)
  - [ ] Extend the current [Contributor Mentorship program](https://make.wordpress.org/community/tag/mentorship-program/) to include mentoring for all contributor roles / [Contributor Working Group](https://make.wordpress.org/community/tag/wpcontributors/)
  - [ ] Improve how do_action uses Open Collective / [Sustainability](https://make.wordpress.org/sustainability/)
    - [ ] [Processes for managing event finances](https://make.wordpress.org/community/handbook/meetup-organizer/event-formats/do_action-charity-hackathon/managing-event-finances/) 
    - [ ] #24 Platform improvements and integrations
