### ISSUE TITLE
Define and document process and structure for collaboration and knowledge share

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#4]
We need to define and document a process and structure for collaboration and knowledge share. Below are specific areas where we need a process. Might make sense to break out into separate issues as we progress. 

### Make Team 

- [ ] Define process for leveraging the following features on https://make.wordpress.org/sustainability/
  - [x] #6
  - [ ] Pinned Posts
  - [ ] Handbook

### Meetings
- [ ] #20

### Slack
Evaluate if/how we should use the following:
- [ ] [Channel Canvas](https://wordpress.slack.com/canvas/C03JNV77Y57): Agenda items, goals, priorities, etc.
- [ ] [Roadmap ideas and suggestions](https://wordpress.slack.com/docs/T024MFP4J/F05NYEDM3AA)
- [ ] [Contributor Day WCUS 2023](https://wordpress.slack.com/docs/T024MFP4J/F05P89CQC06)

### GitHub
Evaluate how we should use the following:
- [ ] [Issues](https://github.com/WordPress/sustainability/issues)
- [ ] [Projects](https://github.com/WordPress/sustainability/projects?query=is%3Aopen)
- [ ] Discussions

### Google Docs
Evaluate if/how we should use the following:
- [ ] [Making WordCamp more environmentally sustainable: Input for the WordCamp handbook](https://docs.google.com/document/d/1LHZVO6IC6fTryL5GK6LVjbluLsly2qo602lQFL5lVLY/edit#heading=h.mtf16p5e5x5v)
- [ ] [Brainstorm: Roadmap WordPress Sustainability Team](https://docs.google.com/document/d/1KVx33UCSSGl4Kra7myE7FkoN9Pg-VwAXqJR4-f3y3kk/edit#heading=h.3dv3c234obuu)

**Comment by noraferreiros** [comment]
What is the difference between this issue and the #13 one? Should we merge them?

**Comment by gusaus** [comment]
Closing out as everything above has since been added to https://make.wordpress.org/sustainability/handbook/ and/or referenced in #5 (or issues referenced there)
