### ISSUE TITLE
Meeting Agenda May 23, 2024

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#43]
Please add agenda items by editing this issue summary or commenting below.

---

_This week’s meeting will be hosted by MEETING_HOST._

Hello everyone. Welcome to the WordPress Sustainability Team Meeting! :calendar: 

Sustainability Team meetings start at [12:00 UTC bi-weekly on Fridays](https://make.wordpress.org/meetings/#sustainability). Anyone is welcome to contribute to the meeting by commenting in Slack threads during the meeting and throughout the following days. Meeting notes will be published by the following Tuesday to also incorporate these asynchronous conversations.

### :mega: Roll Call! 
Who is joining us today? Please say hello, and share a flag or your favorite emoji! Also, please note your WordPress.org profile username as we will use this to record attendees in the notes.

Feel welcome to introduce yourself briefly and share your region (in the thread) :thread:

If you are attending asynchronously, please still add your details to the thread above :point_up_2: It helps to add (async) after your name to reflect on the timings for meetings and how as a team, we can encourage people from across all time zones to be able to participate.

### :arrow_right: News and updates

- item 1
- item 2

### :arrow_right: Looking for feedback
Proposals and discussions in https://make.wordpress.org/sustainability/ and [GitHub](https://github.com/WordPress/sustainability/discussions/categories/general) (General discussions).

- [Project Health Dashboards](https://make.wordpress.org/sustainability/2024/05/15/project-health-dashboards/)
- [Recognizing Contributions and Acknowledging Challenges](https://make.wordpress.org/sustainability/2024/05/10/recognizing-contributions-and-acknowledging-challenges/)
- https://github.com/WordPress/sustainability/discussions/32

### :arrow_right: Meeting Note Takers

- MONTH DAY – 
- MONTH DAY – 
- MONTH DAY – 
- MONTH DAY –

### :arrow_right: Internal priorities
Current [internal priorites](https://github.com/WordPress/sustainability/issues?q=is%3Aissue+is%3Aopen+label%3Aadmin) 

- https://github.com/WordPress/sustainability/issues/5
- https://github.com/WordPress/sustainability/issues/20
  - https://github.com/WordPress/sustainability/issues/34
- https://github.com/WordPress/sustainability/issues/13
- https://github.com/WordPress/sustainability/issues/2

### :arrow_right: Projects
[Projects](https://github.com/orgs/WordPress/projects/134) owned or led by Sustainability team members that are actively being worked on.

- https://github.com/WordPress/sustainability/issues/9
- https://github.com/WordPress/sustainability/issues/22
- https://github.com/WordPress/sustainability/issues/24
- https://github.com/WordPress/sustainability/issues/8
- https://github.com/WordPress/sustainability/issues/33

### :arrow_right: Contribution Goals, Ideas, and Priorities
[Current discussions](https://github.com/WordPress/sustainability/discussions/categories/contribution-goals-and-ideas) around contribution goals and ideas.

- https://github.com/WordPress/sustainability/discussions/39
- https://github.com/WordPress/sustainability/discussions/42
- https://github.com/WordPress/sustainability/discussions/40
- https://github.com/WordPress/sustainability/discussions/41
- https://github.com/WordPress/sustainability/discussions/38
- https://github.com/WordPress/sustainability/discussions/36
- https://github.com/WordPress/sustainability/discussions/35

## :three: Contribution Acknowledgement

- Badges awarded: 
- Props: 

## :four: Open Discussions

Does anyone have an open discussion topic they’d like to bring to the team?

---

You can see all meetings scheduled on [this meeting calendar](https://make.wordpress.org/meetings/#sustainability). If you are new to the Sustainability Team, read through [our handbook](https://make.wordpress.org/sustainability/handbook/)) to get to know the team and how we work. And if you have questions, feel free to reach out in [the #sustainability Slack channel](https://wordpress.slack.com/archives/C03JNV77Y57) at any time.

**Comment by YellowlimeNL** [comment]
Hi @gusaus thank you for putting this agenda together. Am I correct that your intention is to prepare an agenda well in advance that can be used during this week's bi-weekly sustainability meeting?

I've some doubt as you mention thursday and bi-weekly meetings take place on fridays.

If your intention is to use this as a format for the bi-weekly meetings. I have some doubt by having so many topics to be discussed. Knowing the team is still little, but growing, don't you think it's more wise to tacke a few topics and push them really forward? 

Thank you for your support and for sharing your thoughts.

**Comment by noraferreiros** [comment]
Hey! This is a such good work! As I have to publish the agenda today at the latest, and the doubts have not yet been resolved, I will make a version of your proposal for today, Gus, and we will finalise the details for future meetings. Thanks!

**Comment by gusaus** [comment]
Thanks @YellowlimeNL and @noraferreiros 

Glad the template could be of value and agree it's still a work in progress. 

> I have some doubt by having so many topics to be discussed. Knowing the team is still little, but growing, don't you think it's more wise to tacke a few topics and push them really forward?

With regards to the concerns, I tried to address in the related issue/comment https://github.com/WordPress/sustainability/issues/34#issuecomment-2123286473 

With regards to the https://make.wordpress.org/sustainability/2024/05/22/sustainability-chat-agenda-may-24-2024/, while I'm not sure how other teams sync up their agendas (assuming there's a manual cut/paste process), it seems like paring the P2 agenda down to certain issues, projects and discussions increases the chances of omitting priorities (Dashboard initiative https://github.com/WordPress/sustainability/discussions/42, Five for the Future https://github.com/WordPress/sustainability/discussions/39) currently being discussed and/or worked on in our Slack channel and multiple teams and working groups (Sustainability, DEIB, Contributor Working Group, etc.).

If we consider those (and most) projects and programs we're contributing to involve multiple teams, the audience (and potential contributor base) is much larger than the handful of folks able to attend our meetings on a regular basis. 

By surfacing and providing entry points to all our action items, projects, and discussions (the intent of the format is to make that process easy), we can reach a larger group of contributors while 'still' providing a mechanism for real time participants to drill down on anything by creating a thread.

Does that make sense?
