### ISSUE TITLE
Sustainable Events Handbook - Information to check and/or correct

### ISSUE THREAD

**Issue by noraferreiros** [WordPress/sustainability#54]
After [the translation to Spanish](https://docs.google.com/document/d/1K28caiJrpn8pTXheMTV0w7NBwee5kJ7_tX6igghaOdE/edit) of our Sustainable Events Handbook, Nilo Vélez ([@nilovelez](https://profiles.wordpress.org/nilovelez/)), one of the contributors to the Spanish WordPress community, has pointed out some possible errors in the published information.

### **In [Swag and supplies](https://github.com/wordpress/sustainability/edit/trunk/events/swag.md)**

- WordPress Central doesn't send landyards anymore. Organizers have to print them locally. More info [here](https://make.wordpress.org/community/handbook/wordcamp-organizer/planning-details/swag/swag-source-files/).
- Allegedly, there is no way to return leftover material to WordPress Central. But they can help send it to other WordCamps.

### In [Content](https://make.wordpress.org/sustainability/handbook/sustainable-events/content/)

- Officially, it is no longer called Contributor Day, but Community Day.
- "Next Generation" events don't exist anymore. They are all "WordPress Events" now.

---

To Do:

- [x] Verify the information, if in doubt.
- [x] Check if the incorrect information is present on other Handbook pages than the linked ones.
- [x] Correct/re-write the information.

**Comment by noraferreiros** [comment]
Didn't have time myself for "untodoing" this issue, that's why I decided to create it in case anyone else want to do it before I find a moment.

I also wanted to add that it's good news that all the WordPress swag supplies (landyards, badges, stickers, etc.) have to be printed locally. We can add a text explaining this and also encouraging organizers to ask for other WordCamps leftovers before printing, and emphazise on the out-put system for landyards so they can reduce the number of prints.

**Comment by CeliGaroe** [comment]
Thank you for opening the issue, @noraferreiros. I went ahead and created 3 pull requests with the changes, after verifying the information. The only thing that can change is WordPress Central sending lanyards: before they were doing it only in USA, right now they have an issue and they are not doing it but the are considering to do it again, and perhaps from different headquarters depending on the requesting country. So right now I left the text 'when possible' and added the printing locally info. 

Here are the pull request in case someone wants to review my English (@lironmil, perhaps): 

https://github.com/WordPress/sustainability/pull/55
https://github.com/WordPress/sustainability/pull/56
https://github.com/WordPress/sustainability/pull/57

Thanks!
