### ISSUE TITLE
Create Welcome Box

### ISSUE THREAD

**Issue by gusaus** [WordPress/sustainability#6]
We need a Welcome Box like you see on other Team pages - 

https://make.wordpress.org/community/
![Make WordPress Community – Building Local Communities 2023-10-02 19-32-14](https://github.com/WordPress/sustainability/assets/113996/2d2bd5f2-ec38-4fdb-9180-0d0595c5fea1)

https://make.wordpress.org/training/
![Make WordPress Training – WordPress Training Team, providing synchronous and asynchronous WordPress learning 2023-10-02 19-33-08](https://github.com/WordPress/sustainability/assets/113996/e29a4ec2-5ea7-421e-83fc-3d600d7069a6)

Does anyone have experience or know how to create one for https://make.wordpress.org/sustainability/?

**Comment by gusaus** [comment]
I don't have access so don't know what it looks like under the hood. Is there a 'welcome box' block or pattern that Teams can modify and enable?

In terms of what to put on it, I think [Training Team](https://make.wordpress.org/training/) provides a real good example of using a welcome box + a pinned post (maybe we should set up a separate issue for that)

**Comment by sereedmedia** [comment]
The Welcome box displays the content that is on the Handbook page that is set as "Front Page". Once we have the text determined, we can add it.

**Comment by gusaus** [comment]
> Once we have the text determined, we can add it.

@sereedmedia Thanks for getting the ball rolling! 

Seems like we still need structure https://github.com/WordPress/sustainability/issues/4 and some roles defined https://github.com/WordPress/sustainability/issues/2 before new team members can pick up and run with it.

**Comment by noraferreiros** [comment]
Checking the Welcome Box examples I have realized two things:
1. [Community Team](https://make.wordpress.org/community/) has a custom favicon. Should we so?
2. This custom favicon is a custom wapuu ([Translate Team](https://make.wordpress.org/training/) also has one, e.g.). Should we had one too?
3. We could also decide the content of the blog sidebar, in case we consider we need to update/improve it.

These are asks that are not a priority at this time at all, but they came to me now in relation to the Welcome Box need. I don't even know if these tasks should be considered a different issue or if we should decide it together with the content of the Welcome Box.

I only bring more problems/questions and no solutions, sorry xD

**Comment by YellowlimeNL** [comment]
Suggested during the Sustainability Slack Meeting: Create a Gdoc to add text for the Welcome Box. Here it is: https://docs.google.com/document/d/1VFI0bBLTVgX2zWsddRhCrHv8R3rZWNIML661LT6pyVY/edit?usp=sharing

**Comment by meeware** [comment]
[Google Doc](https://docs.google.com/document/d/1VFI0bBLTVgX2zWsddRhCrHv8R3rZWNIML661LT6pyVY/edit) for the drafting of content and layout ideas. https://docs.google.com/document/d/1VFI0bBLTVgX2zWsddRhCrHv8R3rZWNIML661LT6pyVY/edit

**Comment by meeware** [comment]
[Google Doc for content and layout drafting and review](https://docs.google.com/document/d/1VFI0bBLTVgX2zWsddRhCrHv8R3rZWNIML661LT6pyVY/edit?usp=sharing) created by the wonderful and deeply kind @YellowlimeNL has been created.

**Comment by CeliGaroe** [comment]
I tried to mixed both proposed options by Ant Miller and Thijs Buijs at the beginning of the [Google Doc](https://docs.google.com/document/d/1VFI0bBLTVgX2zWsddRhCrHv8R3rZWNIML661LT6pyVY/edit?usp=sharing). 

I wrote it with markdown so we can put it directly in Github when accepted. Could you check my English and add/remove/change anything you feel is needed? 

In order to include it, Se Reed mentioned this in [this issue](https://www.google.com/url?q=https://github.com/WordPress/sustainability/issues/6%23issuecomment-1745493257&sa=D&source=docs&ust=1701882012190137&usg=AOvVaw0hLSPTT50TaKeBEMRYChDl):
The Welcome box displays the content that is on the Handbook page that is set as "Front Page". Once we have the text determined, we can add it.

I can try and do that, but only when is approved by the rest of the team. :) Thanks!

**Comment by noraferreiros** [comment]
![Captura de pantalla 2024-02-11 a las 12 19 58](https://github.com/WordPress/sustainability/assets/43438640/babb5a67-a917-454d-96b4-e99172b21e09)

Taking into account the screenshot (originally shared by Juan Hernando), I'd go with the 2 column option, the first one in the screenshot (even that final "it" is kind of killing me xD). The initial text is too long for the third option, and the second option... Well, just let's forget about this one.
