### ISSUE TITLE
Input for the (WordCamp) handbook around sustainability

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/sustainability#9]
**UPDATE**
In case someone it's joining now the active working document it's [this one](https://docs.google.com/document/d/1uYaGP876SpQ_GLTJRFuI2YFbSh7M9Ku6MizDhHpabgs/edit#heading=h.nllhqa6j8gqd).

---
The [Google doc](https://docs.google.com/document/d/1LHZVO6IC6fTryL5GK6LVjbluLsly2qo602lQFL5lVLY/edit?usp=sharing) with ideas

Would be great if 
[@meeware](https://wordpress.slack.com/team/U0N4RRYBE)
 
[@Nora Ferreirós](https://wordpress.slack.com/team/U02EYQM0ZR8)
 
[@Csaba](https://wordpress.slack.com/team/U02SD78VD)
 
[@Thijs Buijs](https://wordpress.slack.com/team/U03JADH282W)
 and other regulars could skim through and provide some thoughts :point_up::raised_hands::clapper:

**Comment by LittleBigThing** [comment]
I've been looking at the hosting team’s handbook repo and I think it is quite easy to set things up, meaning converting the Google doc to markdown files in the repo.

**Comment by LittleBigThing** [comment]
We have currently the following structure for a page 'WordCamps and other events'?

- Organization
- Venue
- Catering
- Swag
- Sponsors
- Traveling
- Resources, training material, talks (promoting sustainability/ raising awareness/ behavior change)
- Location (geographically and inside a city)
- Marketing & Communications (call for organizers, sponsors)

Location might be merged with Venue (calling it Location and Venue), but besides that it's a nice list of guidelines. :-)

**Comment by LittleBigThing** [comment]
Do we have any more information about how we proceed here? I mean with regard to 

- the content of the file: how do we come to a good enough (not perfect) doc?
- when do we ask other teams to check? WordCamp Organisers?
- technically: we can restructure (see my [comment above](https://github.com/WordPress/sustainability/issues/9#issuecomment-1761427513)) and commit it to the repo and then it’s published and will appear on the [site](https://make.wordpress.org/sustainability/handbook/).
- do we consider a more global structure before we commit? I mean, events is one thing, we will have other information about the team, a section with best sustainability practices for WP sites, ...

**Comment by meeware** [comment]
I think it's important in this instance to apply our advice and content into the material that is already there in the Handbook Therefore while it's been useful to have our own document structure for discussion, this is not a good match for how the WordCamp handbook is structured. I'd suggest as a next step we take a look at the handbook, and identify which sections we're going to add content into. I'd suggest the following pages (and yes, this is clearly a handbook that has grown organically over time, and frankly could probably benefit from a proper clean up and edit):
https://make.wordpress.org/community/handbook/wordcamp-organizer/
https://make.wordpress.org/community/handbook/wordcamp-organizer/become-an-organizer/regional-wordcamps/
https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/venue-and-date/
https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/venue-accessibility-checklist/
https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/venue-contract/
https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/helpful-documents-and-templates/
https://make.wordpress.org/community/handbook/wordcamp-organizer/first-steps/inclusive-and-welcoming-events/
https://make.wordpress.org/community/handbook/wordcamp-organizer/planning-details/
https://make.wordpress.org/community/handbook/wordcamp-organizer/planning-details/food-and-beverage/
https://make.wordpress.org/community/handbook/wordcamp-organizer/planning-details/swag/
https://make.wordpress.org/community/handbook/wordcamp-organizer/planning-details/supplies/
https://make.wordpress.org/community/handbook/wordcamp-organizer/video/
https://make.wordpress.org/community/handbook/wordcamp-organizer/during-wordcamp/ 
https://make.wordpress.org/community/handbook/wordcamp-organizer/faq/
https://make.wordpress.org/community/handbook/wordcamp-organizer/organizer-resources/

In addition the following areas of community outside the handbook could probably benefit from our input:
https://make.wordpress.org/community/handbook/meetup-organizer/meetup-program-basics/
https://make.wordpress.org/community/handbook/virtual-events/
https://make.wordpress.org/community/handbook/community-deputy/other-event-formats/nextgen-wordpress-event/

**Comment by meeware** [comment]
> We have currently the following structure for a page 'WordCamps and other events'?
> 
> * Organization
> * Venue
> * Catering
> * Swag
> * Sponsors
> * Traveling
> * Resources, training material, talks (promoting sustainability/ raising awareness/ behavior change)
> * Location (geographically and inside a city)
> * Marketing & Communications (call for organizers, sponsors)
> 
> Location might be merged with Venue (calling it Location and Venue), but besides that it's a nice list of guidelines. :-)

Honestly this is probably a better content structure than the current handbook, but I think in the first place we have to fit in with the existing structure as much as we can.

**Comment by noraferreiros** [comment]
I agree with @meeware here. Organizers are used to check the current organizers Handbook. If we use a similar structure there would be more chances people check our information, and we will be working toward unifying both in the future. It's also interesting to take the opportunity to make some improvements, as Ant says.

I personally didn't have time to check the organizers handbook yet, but, in my opinion, next step would be defining the structure of our handbook taking the organizers one into account. And, after that, fill it with the content we have in the doc. So, answering Csaba questions:

- _the content of the file: how do we come to a good enough (not perfect) doc?_ I would, first, define the final structure, then, adapt the content. 'Good enough' means to me: the basics so the information starts to be useful. Improve the thing would be another task.
- _when do we ask other teams to check? WordCamp Organisers?_ We can make a call-for-testers when we publish the first version of the handbook (the basic one). This may be useful for also creating a group of contributors for improving the handbook using the feedback. This group may be in charge of managing the testers, collect feedback and turn it into improvement actions.
- _technically: we can restructure (see my https://github.com/WordPress/sustainability/issues/9#issuecomment-1761427513) and commit it to the repo and then it’s published and will appear on the [site](https://make.wordpress.org/sustainability/handbook/)_. Good! I already have shared my opinion about the structure.
- _do we consider a more global structure before we commit? I mean, events is one thing, we will have other information about the team, a section with best sustainability practices for WP sites, ..._ Good question... I would just go for the event handbook and make a decision about this when we have things more tidy. But I'm not sure about this, anyway.


Does all of this make sense?

**Comment by noraferreiros** [comment]
On today's meeting some of us (@LittleBigThing and I, basically) we agreed to start with a basic structure for the general handbook with the next chapters (see the screenshot for clarifying this term):

- Welcome
- Guidance to contribute to the team/How to contribute
- Sustainable events
- Sustainable WP design and development

These are just suggestions, titles can be changes. The idea is just having something to star with and evolve the structure in the future, if we need to. We are aware that some points have no content, don't panic. But it give an idea about the topics we have to work on.

Now, going to this specific topic, we should define the subsections of the Events chapter. At least we now can imagine how it'll look like.

![Captura de pantalla 2023-11-24 a las 13 28 49](https://github.com/WordPress/sustainability/assets/43438640/883d7a19-001a-4a0f-9af6-914888576530)

**Comment by noraferreiros** [comment]
As @LittleBigThing has done a great work creating the most basic structure of the handbook, I think it's time to define the chapters. I'm going to work on a proposal taking [the Organizers Handbook](https://make.wordpress.org/community/handbook/wordcamp-organizer/) as a reference. The goal is to organize our information like this one, so merging in the future will be easier. And it will also be easier for organizers to find information in the meantime. I will first share a proposal for the index so we can discuss about it. Once we have the final one, I suggest we start adding [the information from the document](https://docs.google.com/document/d/1LHZVO6IC6fTryL5GK6LVjbluLsly2qo602lQFL5lVLY/edit) on [GitHub pages](https://github.com/WordPress/sustainability/blob/trunk/events.md).

**Comment by CeliGaroe** [comment]
I created a pull request for the 'Get started'/'How to contribute section' section so it is more helpful to new members: 

https://github.com/WordPress/sustainability/pull/23

I used [Training Team Handbook](https://make.wordpress.org/training/handbook/getting-started/) and [Marketing Team Handbook](https://make.wordpress.org/marketing/handbook/getting-involved/) related sections as models and merge/adapt their information to our team. 

Can you add/correct/remove as you see fit? Thanks! :)

**Comment by CeliGaroe** [comment]
I create a first proposal for the Handbook [About](https://github.com/WordPress/sustainability/blob/trunk/about.md) page. I didn't include it in the manifest, so it is not visible from the Handbook [main page](https://make.wordpress.org/sustainability/handbook/) yet. 

Can you add/correct/remove as you see fit? Thanks! :)

When reviewed and ready, I would love to add it to the manifest myself (it would be my first time doing something like that and I would love to try). I know, very little step for a programmer/developer, but a very big one for a code-ignorant like me (until now...) ;)

**Comment by CeliGaroe** [comment]
@noraferreiros created a [new document]( https://docs.google.com/document/d/1uYaGP876SpQ_GLTJRFuI2YFbSh7M9Ku6MizDhHpabgs/edit?usp=sharing) to work on the WordCamp/Events section of the handbook, our next step on this issue. You can read more in [this Slack thread](https://wordpress.slack.com/archives/C03JNV77Y57/p1705061150242139).

**Comment by noraferreiros** [comment]
I have already put my index or structure proposal in the document @CeliGaroe has shared in the prev comment.

Just for clarifying: I made this just as a way to get this kickstarted. The idea is to use it as a draft and change it as much as we all consider.

In order to avoid an overly personal point of view, I have created a structure mainly based in the sections that were already defined in [the initial document](https://docs.google.com/document/d/1LHZVO6IC6fTryL5GK6LVjbluLsly2qo602lQFL5lVLY/). But I think we should work on things like "Should we have separated sections for "Location", "Venue" and "Traveling" or can they be subsections of a main one?" (just an example). And I also think we should consider adding more sections with information we didn't work on yet (at the end of the document there is a section where we can make suggestions and discuss them).

As I see it, the main next steps are:
1. Defining sections and subsections as they will appear in the public handbook.
2. Writing the final titles and subtitles. They should be short and clear.
3. Leaving content suggestions for everything. And discuss it.
4. Writing the final version of the content as it'll appear in the public handbook.

Let's the party started, mates!

**Comment by noraferreiros** [comment]
How to contribute to the [structure proposal document](https://docs.google.com/document/d/1uYaGP876SpQ_GLTJRFuI2YFbSh7M9Ku6MizDhHpabgs/edit#heading=h.knwjvvz93mgs):

1. Take the information we have already collected in [the initial document](https://docs.google.com/document/d/1LHZVO6IC6fTryL5GK6LVjbluLsly2qo602lQFL5lVLY/) and arrange it in the right "Content suggestion" section. See the "Venue" section as an example.
2. Re-write the existing information as you would include it in the final Handbook.
3. Add new content suggestions, if you feel so (notice that there're already "Other sections to consider" at the end of the document. You can move any of these to the "Sections to include in the Handbook" and work on it, or add any new for other contributors to consider)
4. Propose, discuss or approve changes in the existing texts.
5. Propose, discuss or approve the titles of the sections.
6. Propose, discuss or approve the order or the hierarchy of the sections.

**The aim of the document is to have all the information arranged and ready to be exported directly to GitHub and create the first version of the public Manual.**

**Comment by noraferreiros** [comment]
I have a doubt/suggestion here. I have included at the end of the document a suggestion about creating an "Attendee guide for wordcamping more sustainably" (not my idea). Reviewing the initial document I have noticed that there are already many ideas attendee-addressed. Should we create a section inside the handbook we are working on or should we make a separated one? I do believe we have to do this kind of guidelines for attendees anyway.

**Comment by ciudadanoB** [comment]
> I have a doubt/suggestion here. I have included at the end of the document a suggestion about creating an "Attendee guide for wordcamping more sustainably" (not my idea). Reviewing the initial document I have noticed that there are already many ideas attendee-addressed. Should we create a section inside the handbook we are working on or should we make a separated one? I do believe we have to do this kind of guidelines for attendees anyway.

I would love to have a separate section just for attendees. As an organizer, I know that all the info in the handbook is going to be useful for having an overall sustainable event. But it would be nice to have somewhere to redirect attendees when telling them about our goals. Like "We want to create a sustainable event, but we need your help, here you can check some tips and recommendations, because this is a community effort". And that way they don't have to scan every section.

**Comment by CeliGaroe** [comment]
> I have a doubt/suggestion here. I have included at the end of the document a suggestion about creating an "Attendee guide for wordcamping more sustainably" (not my idea). Reviewing the initial document I have noticed that there are already many ideas attendee-addressed. Should we create a section inside the handbook we are working on or should we make a separated one? I do believe we have to do this kind of guidelines for attendees anyway.

Perhaps a good option would be to have a general Events Sustainability section in the handbook and, inside it, one subsection for organisers and another for attendees. And we replicate the structure we set for the organisers one in the attendees one, but with less sub-sub-sections, as there are things (like location) that do not apply.

**Comment by CeliGaroe** [comment]
> > I have a doubt/suggestion here. I have included at the end of the document a suggestion about creating an "Attendee guide for wordcamping more sustainably" (not my idea). Reviewing the initial document I have noticed that there are already many ideas attendee-addressed. Should we create a section inside the handbook we are working on or should we make a separated one? I do believe we have to do this kind of guidelines for attendees anyway.
> 
> Perhaps a good option would be to have a general Events Sustainability section in the handbook and, inside it, one subsection for organisers and another for attendees. And we replicate the structure we set for the organisers one in the attendees one, but with less sub-sub-sections, as there are things (like location) that do not apply.

Indeed, I left an example of something similar in the travel section: https://docs.google.com/document/d/1uYaGP876SpQ_GLTJRFuI2YFbSh7M9Ku6MizDhHpabgs/edit#heading=h.8tg7jlepdyfs

**Comment by noraferreiros** [comment]
Just for the record, I agree with the comment @CeliGaroe left in the doc about collecting and sorting the information for both organizers and attendees under the same section for now  and, when ready, split them, since they will have the same structure (see previous comment for better understanding).

**Comment by lironmil** [comment]
[Final](https://docs.google.com/document/d/16DDONfJ2U4shL40DYX8N-qCxm39H20iFiWX2tiQEsYA/edit?usp=sharing) version for review

@CeliGaroe @noraferreiros: 
I've finished editing the handbook and left one comment on the updated version. 

The big changes: 
- I deleted "first steps". I think this content is international-event-level and might hold back the readers. 
- Inspiration: I turned it into a short inspirational text, used information from links we can't use, and added links where possible. 
- I also revised the swag list: deleted, added, and reordered.

**Comment by CeliGaroe** [comment]
Thanks @lironmil! I created the files inside the ‘event’ folder and published them in the handbook for making it easier for anyone else to review the content and structure. It is already there! 😊

**Comment by noraferreiros** [comment]
Thank you both!! You have done a fantastic job!

**Comment by meeware** [comment]
Closing this out with agreement of @noraferreiros and the Handbook table at contributor day 2024 We'll have a new issue for the handbook input today.
